{% set name = "pexsi" %}
{% set version = "2.0.0" %}
{% set build = 1 %}
{% set mpi = mpi or "mpich" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://bitbucket.org/berkeleylab/{{ name }}/downloads/{{ name }}_v{{ version }}.tar.gz
  sha256: c5c83c2931b2bd0c68a462a49eeec983e78b5aaa1f17dd0454de4e27b91ca11f
  patches:
    - cmake-shared-lib.patch
    - cmake-find-linalg.patch  # [build_platform != target_platform]

build:
  number: {{ build }}
  skip: True  # [win]
  script:
    - set -ex
    - >
       export
       CXX="mpicxx"
       CC="mpicc"
       FC="mpifort"
       OPAL_PREFIX=$PREFIX  # [mpi == "openmpi"]
       OMPI_MCA_plm=isolated  # [mpi == "openmpi"]
       OMPI_MCA_btl_vader_single_copy_mechanism=none  # [mpi == "openmpi"]
       OMPI_MCA_rmaps_base_oversubscribe=yes  # [mpi == "openmpi"]
    - >
       cmake
       ${CMAKE_ARGS}
       -DBUILD_SHARED_LIBS=ON
       -DPEXSI_ENABLE_OPENMP=ON
       -DBLAS_LIBRARIES=$PREFIX/lib/libblas${SHLIB_EXT}
       -DLAPACK_LIBRARIES=$PREFIX/lib/liblapack${SHLIB_EXT}
       -G Ninja -B _build
    - cmake --build _build
    - ctest --test-dir _build --output-on-failure  # [build_platform == target_platform]
    - cmake --install _build

  {% set mpi_prefix = "mpi_" + mpi %}
  string: "{{ mpi_prefix }}_h{{ PKG_HASH }}_{{ build }}"

  run_exports:
    - {{ pin_subpackage(name, max_pin='x.x') }} {{ mpi_prefix }}_*

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
    - {{ compiler('fortran') }}
    - cmake
    - ninja
    - llvm-openmp  # [osx]
    - libgomp  # [linux]
    - {{ mpi }}  # [mpi == "openmpi" and build_platform != target_platform]
  host:
    - {{ mpi }}
    - parmetis
    - superlu_dist
    - libblas
    - liblapack
  run:
    - {{ mpi }}
    - parmetis


test:
  commands:
    - test -f $PREFIX/lib/lib{{ name }}${SHLIB_EXT}
    - test -f $PREFIX/include/p{{ name }}.hpp
    - test -f $PREFIX/include/c_{{ name }}_interface.h
    - test -f $PREFIX/include/f_p{{ name }}_interface.mod

about:
  home: https://pexsi.readthedocs.io/en/latest/
  license: BSD-3-Clause
  license_family: BSD
  license_file:
    - LICENSE
  summary: Pole expansion and selected inversion
  dev_url: https://bitbucket.org/berkeleylab/pexsi

extra:
  recipe-maintainers:
    - awvwgk
